# Generated by Django 5.0.4 on 2026-03-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_compliancedocument_tenant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
