# Generated by Django 5.0.4 on 2026-03-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='request_type',
            field=models.CharField(default='Technical', max_length=32),
        ),
    ]
