# Generated by Django 5.0.4 on 2026-03-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_maintenancerequest_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='scheduled', max_length=16),
        ),
    ]
