# Generated by Django 5.0.4 on 2026-03-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='units/'),
        ),
    ]
