# Generated by Django 5.0.4 on 2026-03-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_unit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='tenant_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
