# Generated by Django 5.1.15 on 2026-03-19 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_unit_tenant_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
