# Generated by Django 5.1.15 on 2026-03-29 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_payment_expiration_date_payment_starting_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='starting_date',
        ),
    ]
