# Generated by Django 5.1.15 on 2026-04-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_maintenancerequest_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lease_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lease_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('expiring_soon', 'expiring_soon')], default='pending', max_length=16),
        ),
    ]
