# Generated by Django 5.1.15 on 2026-04-23 09:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_compliancerequest_delete_commercialunit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='scheduled', max_length=16),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('expiring_soon', 'expiring_soon')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('success', 'success'), ('warning', 'warning'), ('info', 'info')], default='info', max_length=16),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('failed', 'failed'), ('unpaid', 'unpaid')], default='completed', max_length=16),
        ),
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('occupied', 'occupied'), ('reserved', 'reserved'), ('maintenance', 'maintenance')], default='available', max_length=16),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('staff', 'staff'), ('tenant', 'tenant')], max_length=16),
        ),
        migrations.CreateModel(
            name='ArchivedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('user', 'User'), ('transaction', 'Transaction'), ('unit', 'Unit'), ('document', 'Document'), ('event', 'Event'), ('maintenance', 'Maintenance'), ('compliance', 'Compliance')], db_index=True, max_length=32)),
                ('original_id', models.CharField(max_length=64)),
                ('data', models.JSONField()),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deleted_at'],
            },
        ),
        migrations.DeleteModel(
            name='ComplianceRequest',
        ),
    ]
