# Generated by Django 6.0.5 on 2026-05-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_appointment_status_alter_document_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('rejected', 'rejected')], default='active', max_length=16),
        ),
    ]
