# Generated by Django 6.0.5 on 2026-05-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_payment_tenant_name_alter_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tenant_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
