# Generated by Django 6.0.5 on 2026-05-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_appointment_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='category',
            field=models.CharField(default='General', max_length=64),
        ),
    ]
