# Generated by Django 6.0.5 on 2026-05-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_appointment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='none', max_length=32),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('failed', 'failed'), ('unpaid', 'unpaid')], default='unpaid', max_length=16),
        ),
    ]
