// MOCK DATA SERVICE
// This file contains mock data for development and demonstration
// Replace these with actual API calls to Django backend in production

export const mockUsers = [
  {
    id: '1',
    email: 'admin@skymall.com',
    firstName: 'Admin',
    lastName: 'User',
    role: 'admin',
    phone: '+1 (555) 100-1000',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Admin',
    createdAt: '2025-01-15',
    status: 'active',
  },
  {
    id: '2',
    email: 'staff@skymall.com',
    firstName: 'Staff',
    lastName: 'Member',
    role: 'staff',
    phone: '+1 (555) 200-2000',
    department: 'Operations',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Staff',
    createdAt: '2025-02-01',
    status: 'active',
  },
  {
    id: '3',
    email: 'john.tenant@email.com',
    firstName: 'John',
    lastName: 'Tenant',
    role: 'tenant',
    phone: '+1 (555) 123-4567',
    unitNumber: 'A-105',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    createdAt: '2025-01-20',
    status: 'active',
  },
  {
    id: '4',
    email: 'sarah.jones@email.com',
    firstName: 'Sarah',
    lastName: 'Jones',
    role: 'tenant',
    phone: '+1 (555) 234-5678',
    unitNumber: 'B-202',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    createdAt: '2025-02-10',
    status: 'active',
  },
  {
    id: '5',
    email: 'mike.wilson@email.com',
    firstName: 'Mike',
    lastName: 'Wilson',
    role: 'staff',
    phone: '+1 (555) 345-6789',
    department: 'Maintenance',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
    createdAt: '2025-01-25',
    status: 'active',
  },
];

export const mockComplianceDocuments = [
  {
    id: '1',
    tenantId: '3',
    tenantName: 'John Tenant',
    documentType: 'Business License',
    fileName: 'business-license-2026.pdf',
    uploadDate: '2026-02-15',
    expiryDate: '2027-02-15',
    status: 'approved',
    notes: 'All documents verified',
  },
  {
    id: '2',
    tenantId: '4',
    tenantName: 'Sarah Jones',
    documentType: 'Insurance Certificate',
    fileName: 'insurance-cert.pdf',
    uploadDate: '2026-02-20',
    expiryDate: '2026-12-31',
    status: 'pending',
    notes: '',
  },
  {
    id: '3',
    tenantId: '3',
    tenantName: 'John Tenant',
    documentType: 'Fire Safety Certificate',
    fileName: 'fire-safety.pdf',
    uploadDate: '2026-01-10',
    expiryDate: '2026-06-10',
    status: 'expiring_soon',
    notes: 'Renewal required',
  },
];

export const mockAppointments = [
  {
    id: '1',
    title: 'Unit Inspection - A-105',
    date: '2026-03-05',
    time: '10:00 AM',
    duration: '1 hour',
    type: 'inspection',
    status: 'scheduled',
    attendees: ['John Tenant', 'Staff Member'],
    location: 'Unit A-105',
  },
  {
    id: '2',
    title: 'Lease Renewal Meeting',
    date: '2026-03-08',
    time: '2:00 PM',
    duration: '30 minutes',
    type: 'meeting',
    status: 'scheduled',
    attendees: ['Sarah Jones', 'Admin User'],
    location: 'Office',
  },
  {
    id: '3',
    title: 'Maintenance Review',
    date: '2026-03-10',
    time: '9:00 AM',
    duration: '2 hours',
    type: 'maintenance',
    status: 'scheduled',
    attendees: ['Mike Wilson', 'Staff Member'],
    location: 'Building B',
  },
];

export const mockOperationRequests = [
  {
    id: '1',
    title: 'HVAC System Malfunction - Floor 3',
    type: 'Technical',
    priority: 'high',
    status: 'in_progress',
    createdBy: 'Staff Member',
    assignedTo: 'Mike Wilson',
    createdAt: '2026-03-01',
    description: 'Air conditioning not working properly on floor 3',
  },
  {
    id: '2',
    title: 'Access Control Update',
    type: 'Security',
    priority: 'medium',
    status: 'open',
    createdBy: 'Admin User',
    assignedTo: 'Staff Member',
    createdAt: '2026-02-28',
    description: 'Update access codes for new tenants',
  },
  {
    id: '3',
    title: 'Parking Space Allocation',
    type: 'Administrative',
    priority: 'low',
    status: 'closed',
    createdBy: 'Sarah Jones',
    assignedTo: 'Staff Member',
    createdAt: '2026-02-25',
    description: 'Request for additional parking space',
  },
];

export const mockInvoices = [
  {
    id: 'INV-001',
    tenantId: '3',
    tenantName: 'John Tenant',
    unitNumber: 'A-105',
    amount: 2500.00,
    dueDate: '2026-03-15',
    status: 'paid',
    issueDate: '2026-03-01',
    description: 'Monthly Rent - March 2026',
  },
  {
    id: 'INV-002',
    tenantId: '4',
    tenantName: 'Sarah Jones',
    unitNumber: 'B-202',
    amount: 3200.00,
    dueDate: '2026-03-15',
    status: 'unpaid',
    issueDate: '2026-03-01',
    description: 'Monthly Rent - March 2026',
  },
  {
    id: 'INV-003',
    tenantId: '3',
    tenantName: 'John Tenant',
    unitNumber: 'A-105',
    amount: 2500.00,
    dueDate: '2026-02-15',
    status: 'paid',
    issueDate: '2026-02-01',
    description: 'Monthly Rent - February 2026',
  },
];

export const mockPayments = [
  {
    id: 'PAY-001',
    invoiceId: 'INV-001',
    tenantName: 'John Tenant',
    amount: 2500.00,
    paymentDate: '2026-03-10',
    paymentMethod: 'Bank Transfer',
    status: 'completed',
    transactionId: 'TXN-20260310-001',
  },
  {
    id: 'PAY-002',
    invoiceId: 'INV-003',
    tenantName: 'John Tenant',
    amount: 2500.00,
    paymentDate: '2026-02-12',
    paymentMethod: 'Credit Card',
    status: 'completed',
    transactionId: 'TXN-20260212-001',
  },
];

export const mockCommercialUnits = [
  {
    id: '1',
    unitNumber: 'A-105',
    floor: 1,
    size: 150,
    type: 'Retail',
    rentalRate: 2500.00,
    status: 'occupied',
    tenantId: '3',
    tenantName: 'John Tenant',
    leaseStartDate: '2025-06-01',
    leaseEndDate: '2027-05-31',
  },
  {
    id: '2',
    unitNumber: 'B-202',
    floor: 2,
    size: 200,
    type: 'Food',
    rentalRate: 3200.00,
    status: 'occupied',
    tenantId: '4',
    tenantName: 'Sarah Jones',
    leaseStartDate: '2025-08-01',
    leaseEndDate: '2027-07-31',
  },
  {
    id: '3',
    unitNumber: 'A-107',
    floor: 1,
    size: 120,
    type: 'Service',
    rentalRate: 2000.00,
    status: 'available',
    tenantId: null,
    tenantName: null,
    leaseStartDate: null,
    leaseEndDate: null,
  },
  {
    id: '4',
    unitNumber: 'C-301',
    floor: 3,
    size: 180,
    type: 'Retail',
    rentalRate: 2800.00,
    status: 'reserved',
    tenantId: null,
    tenantName: null,
    leaseStartDate: null,
    leaseEndDate: null,
  },
  {
    id: '5',
    unitNumber: 'B-205',
    floor: 2,
    size: 90,
    type: 'Service',
    rentalRate: 1800.00,
    status: 'maintenance',
    tenantId: null,
    tenantName: null,
    leaseStartDate: null,
    leaseEndDate: null,
  },
];

export const mockMaintenanceRequests = [
  {
    id: '1',
    tenantId: '3',
    tenantName: 'John Tenant',
    unitNumber: 'A-105',
    title: 'Leaking Faucet',
    description: 'The bathroom faucet is leaking continuously',
    priority: 'medium',
    status: 'in_progress',
    createdAt: '2026-02-28',
    assignedTo: 'Mike Wilson',
  },
  {
    id: '2',
    tenantId: '4',
    tenantName: 'Sarah Jones',
    unitNumber: 'B-202',
    title: 'Air Conditioning Not Working',
    description: 'The AC unit is not cooling properly',
    priority: 'high',
    status: 'pending',
    createdAt: '2026-03-01',
    assignedTo: null,
  },
  {
    id: '3',
    tenantId: '3',
    tenantName: 'John Tenant',
    unitNumber: 'A-105',
    title: 'Light Bulb Replacement',
    description: 'Need replacement for ceiling light',
    priority: 'low',
    status: 'completed',
    createdAt: '2026-02-20',
    assignedTo: 'Mike Wilson',
    completedAt: '2026-02-22',
  },
];

export const mockRevenueData = [
  { month: 'Jan', revenue: 125000, expenses: 45000 },
  { month: 'Feb', revenue: 132000, expenses: 48000 },
  { month: 'Mar', revenue: 128000, expenses: 46000 },
  { month: 'Apr', revenue: 145000, expenses: 52000 },
  { month: 'May', revenue: 138000, expenses: 49000 },
  { month: 'Jun', revenue: 155000, expenses: 55000 },
];

export const mockNotifications = [
  {
    id: '1',
    title: 'New Payment Received',
    message: 'Payment of $2,500 received from John Tenant',
    type: 'success',
    read: false,
    createdAt: '2026-03-02T10:30:00',
  },
  {
    id: '2',
    title: 'Document Expiring Soon',
    message: 'Fire Safety Certificate for Unit A-105 expires in 30 days',
    type: 'warning',
    read: false,
    createdAt: '2026-03-02T09:15:00',
  },
  {
    id: '3',
    title: 'Maintenance Request Submitted',
    message: 'New maintenance request from Sarah Jones - Unit B-202',
    type: 'info',
    read: true,
    createdAt: '2026-03-01T14:20:00',
  },
];
